parameters:
#    acme_post.example.class: Acme\PostBundle\Example

services:
#    acme_post.example:
#        class: %acme_post.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
